import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/navBar/NavBar";
import AuthProvider from "@/contexts/auth";

const font = Montserrat({ subsets: ["latin"], weight: ["300", "400", "600", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={font.className}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <NavBar/>
            <main className="flex-grow">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
